[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"


[project]
name = "extract-contact-information"
authors = [
    {name = "Jeremie Barhabazi", email = "jbarh086@uottawa.ca"}
]
maintainers = [
    {name = "Jeremie Barhabazi", email = "jbarh086@uottawa.ca"}
]
description = "A command-line tool that extracts email address and phone numbers from a web page."
version = "0.1.0"
dependencies = [
    "click>=8", 
    "requests>=2.34.0"
]
requires-python = ">= 3.14"


[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov",
    "pytest-mock",
    "ruff",
    "mypy"
]

[tool.pytest.ini_options]
addopts = "--cov=src --cov-report=term-missing --cov-report=html"
testpaths = ["tests"]

[tool.coverage.run]
source = ["src"]
branch = true

[tool.coverage.report]
show_missing = true
skip_empty = true
fail_under = 80
exclude_lines = [
    "pragma: no cover",
    "if __name__ == .__main__.:",
    "raise NotImplementedError"
]

[tool.coverage.html]
directory = "htmlcov"


[tool.ruff]
# Set the maximum line length to 79.
line-length = 79

[tool.ruff.lint]
# Add the `line-too-long` rule to the enforced rule set. By default, Ruff omits rules that
# overlap with the use of a formatter, like Black, but we can override this behavior by
# explicitly adding the rule.
extend-select = ["E501"]

[tool.mypy]
# Enable strict mode, which includes several other checks
strict = true
# You can add other configurations here, e.g.,
# disallow_untyped_defs = true
# ignore_missing_imports = true