[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"


[project]
name = "extract-contact-information"
authors = [
    {name = "Jeremie Barhabazi", email = "jbarh086@uottawa.ca"}
]
maintainers = [
    {name = "Jeremie Barhabazi", email = "jbarh086@uottawa.ca"}
]
description = "A command-line tool that extracts email address and phone numbers from a web page."
version = "0.1.0"
dependencies = [
    "click>=8", 
    "requests>=2.34.0"
]
requires-python = ">= 3.14"


[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov",
    "pytest-mock",
    "ruff",
    "black",
    "mypy",
    "types-requests",
    "bandit"
]

[tool.pytest.ini_options]
addopts = "--cov=src --cov-report=term-missing --cov-report=html"
testpaths = ["tests"]

[tool.coverage.run]
source = ["src"]
branch = true

[tool.coverage.report]
show_missing = true
skip_empty = true
fail_under = 80
exclude_lines = [
    "pragma: no cover",
    "if __name__ == .__main__.:",
    "raise NotImplementedError"
]
omit = [
    "src/__init__.py"
]

[tool.coverage.html]
directory = "htmlcov"


[tool.ruff]
target-version= "py314"
line-length = 88
exclude = [
    ".git",
    ".venv",
    "venv",
    "build",
    "dist",
]

[tool.ruff.lint]
# Enable:
# E/F = pycodestyle + Pyflakes
# I   = import sorting
# B   = bugbear (common Python pitfalls)
# UP  = modernize Python code
select = ["E", "F", "I", "B", "UP"]

# Rules that are intentionally disabled
ignore = [
    "E501",  # Line length is handled by Black
]

[tool.ruff.lint.isort]
# Make imports look like Black-compatible, conventional Python imports
combine-as-imports = true

[tool.black]
line-length = 88
target-version = ["py312"]

# Files/directories Black should ignore
exclude = '''
/(
    \.git
  | \.venv
  | venv
  | build
  | dist
)/
'''

[tool.mypy]
# Enable strict mode, which includes several other checks
strict = true
# You can add other configurations here, e.g.,
# disallow_untyped_defs = true
# ignore_missing_imports = true
warn_unused_configs = true
warn_return_any = true
ignore_missing_imports = true

[tool.bandit]
exclude_dirs = [".venv", "__pycache__", "build", "dist"]
skips = ["B101"] 
 

[project.scripts]
contact-extractor = "contact_extractor:extract_contact_information"
